# ベースイメージとしてAmazon Linux 2を使用
FROM amazonlinux:2

# 必要なパッケージのアップデートとインストール
RUN yum -y update && \
    yum -y install openssh-clients iputils procps nfs-utils && \
    curl -L -O https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.rpm && \
    rpm -i amazon-corretto-8-x64-linux-jdk.rpm


# Javaの環境変数設定
ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-amazon-corretto
ENV PATH $JAVA_HOME/bin:$PATH

# 共有ディレクトリの作成とエクスポート設定
RUN mkdir -p /srv/nfs_share && \
    chmod 777 /srv/nfs_share && \
    echo "/srv/nfs_share *(rw,sync,no_subtree_check,no_root_squash)" >> /etc/exports

# 確認用にJavaとSSHのバージョンを表示する
CMD ["bash", "-c", "java -version && ssh -V && rpcbind && exportfs -r && nfsd && tail -f /dev/null"]
