# ベースイメージとしてAmazon Linux 2を使用
FROM amazonlinux:2

# 必要なパッケージのアップデートとインストール
RUN yum -y update && \
    yum -y install openssh-clients iputils procps samba && \
    curl -L -O https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.rpm && \
    rpm -i amazon-corretto-8-x64-linux-jdk.rpm

# Javaの環境変数設定
ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-amazon-corretto
ENV PATH $JAVA_HOME/bin:$PATH

# 共有フォルダの作成とSamba設定
# /etc/samba/smb.conf
# [global]
#    map to guest = Bad User
# [share]
#     path = /srv/samba/share
#     browseable = yes
#     read only = no
#     guest ok = yes
RUN mkdir -p /srv/samba/share && \
    chmod 777 /srv/samba/share && \
    echo -e '[global]\n   map to guest = Bad User\n[share]\n   path = /srv/samba/share\n   browseable = yes\n   read only = no\n   guest ok = yes' > /etc/samba/smb.conf

# 確認用にJavaとSSHのバージョンを表示する
CMD ["bash", "-c", "java -version && ssh -V && smbd && tail -f /dev/null"]
