# ベースイメージとしてAmazon Linux 2を使用
FROM amazonlinux:2

# 必要なパッケージのアップデートとインストール
RUN yum -y update && \
    yum -y install openssh-clients iputils procps cronie-noanacron logrotate && \
    curl -L -O https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.rpm && \
    rpm -i amazon-corretto-8-x64-linux-jdk.rpm


# Javaの環境変数設定
ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-amazon-corretto
ENV PATH $JAVA_HOME/bin:$PATH

RUN mkdir /tmp/test

# お試しcronジョブの設定
RUN echo '* * * * * echo "cron job executed at $(date)" >> /tmp/test/cron_test.log' > /etc/crontab && crontab /etc/crontab

# logrotateの設定ファイル作成
# - ファイルサイズが1KBを超えた場合にローテーションを行います。
# - 7世代分の古いログファイルを保持します。
# - gzip 形式で圧縮されます。
# - ログファイルが存在しなくてもエラーを出さずにスキップします。
# - ログファイルが空でない場合のみローテーションを行います。
RUN echo -e '/tmp/test/cron_test.log {\n\
    size 1k\n\
    rotate 7\n\
    compress\n\
    missingok\n\
    notifempty\n\
    \n}' > /etc/logrotate.d/cron_test

# 確認用にJavaとSSHのバージョンを表示する
CMD ["bash", "-c", "java -version && ssh -V && crond && tail -f /dev/null"]
